#!/bin/zsh

if which atuin >&/dev/null; then
    # Either set ATUIN_NOBIND=true and then bind C-r yourself, or
    # use --disable-up-arrow which binds C-r and might introduce
    # additional bindings in the future.

    unset ATUIN_NOBIND
    #export ATUIN_NOBIND="true"

    eval "$(atuin init zsh --disable-up-arrow)"

    if [ "$ATUIN_NOBIND" = true ]; then
        bindkey '^r' atuin-search

        # bind to the up key, which depends on terminal mode
        #bindkey '^[[A' atuin-up-search
    fi
fi
