#!/bin/zsh

if which atuin >&/dev/null; then
    #unset ATUIN_NOBIND
    export ATUIN_NOBIND="true"

    eval "$(atuin init zsh)"

    if [ "$ATUIN_NOBIND" = true ]; then
        bindkey '^r' atuin-search

        # bind to the up key, which depends on terminal mode
        #bindkey '^[[A' atuin-up-search
    fi
fi
