#!/bin/bash

# Not using this for now
return 1  # Carry on processing other hooks

notion_enhanced=~/software/web/Notion-Enhanced.AppImage

if ! [ -x "$notion_enhanced" ]; then
    return 1  # Carry on processing other hooks
fi


case "$1" in
    https://www.notion.so/*)
        path="${1#https://www.notion.so/}"
        $notion_enhanced notion://"$path" &
        set --
        return 0
        ;;
esac
