#!/bin/bash

# requires export BASH_ENV=~/.bashenv which will mean a performance hit,
# so not worth doing in general

# PS4="+\${BASH_SOURCE/\$HOME/\~}@\${LINENO}(\${FUNCNAME[0]}): "

# Make it easy to load PS4
alias loadps4='source ${HOME}/.bashrc.d/prompt-ps4.bashrc; echo PS4=$PS4'

# [!] Don't change to double quotes
export PS4='+\011\e[1;30m\t  \e[1;34m${BASH_SOURCE}\e[0m:\e[1;36m${LINENO}\e[0m \011 ${FUNCNAME[0]:+\e[0;35m${FUNCNAME[0]}\e[1;30m()\e[0m:\011 }'

