#!/bin/sh
#
# %% Executable hook %%

cat <<EOF
PATH=$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin

# This is redundant I think
#MAILTO=${USER:-$USERNAME}

# coral postfix won't accept mail from anybody
#MAILTO=moosehall-cron@adamspiers.org

MAILTO=adam

#min  hr dom mon dow    command
EOF
