#!/bin/bash

confdir=.cron.d
config=$HOME/.crontab

source "$ZDOTDIR/lib/libhooks.sh"

crontab -l > "$config"

# FIXME: doesn't work if no crontab exists
if ! rebuild_config "$config" "$confdir"; then
    echo "ERROR: failed to rebuild $config from $confdir" >&2
    exit 1
fi

if ( echo; cat "$config" ) | crontab -; then
    echo "Reinstalled user's crontab"
else
    echo "WARNING: Failed to reinstall user's crontab" >&2
    exit 1
fi
