#!/bin/bash

confdir=.cron.d
config=$HOME/.crontab

source "$ZDOTDIR/lib/libhooks.sh"

crontab -l > "$config"

if rebuild_config "$config" "$confdir"; then
    if ( echo; cat "$config" ) | crontab -; then
        echo "Reinstalled user's crontab"
    else
        echo "WARNING: Failed to reinstall user's crontab" >&2
    fi
fi
